name: tic_tac_toe
description: Jogo da Velha 2.0
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_animate: ^4.0.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/move.mp3
    - assets/sounds/win_subboard.mp3
    - assets/sounds/win_game.mp3
    - assets/sounds/draw.mp3